source 'https://rubygems.org'

gem 'smashing'

## Uncomment this if you want to see use the twitter widget.
# gem 'twitter', '>= 5.9.0'
gem 'concurrent-ruby', '~> 1.0', '>= 1.0.5'
gem 'rest-client', '~> 2.1'
